micronaut:
  application:
    name: restaurantClient

kafka.bootstrap.servers: localhost:29092

mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

app:
  generate-order-delay: "10m"
  kafka.topic:
    dish-prepare: dish-prepare
    recipe-create: recipe-create
    order-create: order-create

mongo:
  collection: recipe
